"""Adapt established local saved-output kernel checker to actual remote closure; no torch/math."""
import hashlib,json,os,subprocess,sys,tarfile
from pathlib import Path
from datetime import datetime
O=Path(__file__).resolve().parent;T=O.parent;R=Path('/srv/encbank/legacy_workspace');C=T/'completion_collection_attempt1/archive_collection/closed_bundle';W=C/'saved_attempt1/worker';P=C/'saved_attempt1'
def stamp():return datetime.now().astimezone().isoformat()
def sha(p):
 with Path(p).open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def read(p):return json.loads(Path(p).read_text(encoding='utf-8-sig'))
def save(p,v):Path(p).write_bytes((json.dumps(v,indent=2)+'\n').encode())
if '--child' not in sys.argv:
 start=stamp();argv=[sys.executable,'-X','utf8','-B',str(Path(__file__).resolve()),'--child']
 with (O/'stdout.log').open('xb') as stdout,(O/'stderr.log').open('xb') as stderr:
  child=subprocess.Popen(argv,stdout=stdout,stderr=stderr,cwd=R);code=child.wait()
 receipt={'status':'completed' if code==0 else 'failed','argv':argv,'pid':child.pid,'actual_exit_code':code,'actual_parent_wait':True,'process_exit_observed':child.returncode is not None,'started_at':start,'finished_at':stamp(),'checker_sha256':sha(__file__),'report_sha256':sha(O/'report.json') if (O/'report.json').exists() else None,'stdout_sha256':sha(O/'stdout.log'),'stderr_sha256':sha(O/'stderr.log'),'GPU_or_CPU_math_rerun':False}
 save(O/'execution_receipt.json',receipt);print(json.dumps(receipt));raise SystemExit(code)
start=stamp();checks={};bindings={}
def bind(p,expected=None):
 p=Path(p).resolve();assert p.is_relative_to(R.resolve());digest=sha(p);bindings[p.relative_to(R).as_posix()]=digest
 if expected is not None:assert digest==expected,str(p)
 return digest
plan_hash=bind(T/'plan.json','a220f80a2b011d64350e69ef64c8bb0b777392c32b6374e4bc2831355c30e4c9')
plan,transport,worker,result,batch,shell,observation,manifest=[read(p) for p in [T/'plan.json',W/'execution.json',W/'worker.json',W/'result.json',P/'batch_status.json',P/'shell_exit.json',C/'observation.json',C/'copy_manifest.json']]
for p in [W/'execution.json',W/'worker.json',W/'result.json',W/'stdout.log',W/'stderr.log',P/'batch_status.json',P/'shell_exit.json',C/'observation.json',C/'copy_manifest.json',C/'sacct.raw',C/'slurm_logs/slurm-24607.out',C/'slurm_logs/slurm-24607.err']:bind(p)
archive=C.parent/'complete_saved_run.tar';bind(archive,manifest['complete_archive']['sha256'])
archive_hashes={}
with tarfile.open(archive,'r:') as saved_tar:
 for member in saved_tar:
  if member.isfile():
   assert member.name not in archive_hashes and not member.issym() and not member.islnk()
   with saved_tar.extractfile(member) as stream:archive_hashes[member.name]=hashlib.file_digest(stream,'sha256').hexdigest()
checks['all_copied_output_and_log_hashes_match_terminal_remote_bytes']=archive_hashes==manifest['archive_member_sha256'] and {k[len('run/attempt1/'):]:v for k,v in archive_hashes.items() if k.startswith('run/attempt1/')}==manifest['outputs']==observation['remote_actual_hashes']['outputs'] and manifest['extracted_scientific_outputs']=={p.relative_to(P).as_posix():sha(p) for p in P.rglob('*') if p.is_file()} and all(sha(C/'slurm_logs'/n)==h for n,h in manifest['slurm_logs'].items())
collection_receipt=C.parent/'execution_receipt.json';bind(collection_receipt);collection=read(collection_receipt)
checks['read_only_archive_collection_closed_without_scientific_rerun']=collection['status']=='complete_archive_all_hashes_match_scientific_outputs_extracted' and collection['actual_exit_code']==0 and collection['actual_parent_wait'] and collection['process_exit_observed'] and collection['GPU_or_model_or_numerical_rerun'] is False
checks['actual_native_parent_shell_and_Slurm_zero_closure']=transport['worker_exit_code']==0 and transport['actual_parent_wait'] and transport['process_exit_observed'] and transport['worker_pid']==worker['pid'] and batch['status']=='tiny_kernel_checks_complete_shell_and_slurm_exit_pending' and batch['stages'][0]['actual_exit_code']==0 and shell['actual_shell_exit_code']==0 and shell['shell_exit_trap_observed'] and all(any(line.startswith(j+'|COMPLETED|0:0|') for line in observation['sacct']['stdout'].splitlines()) for j in ['24607','24607.batch'])
checks['same_plan_and_successful_worker_result']=all(v['plan_sha256']==plan_hash for v in [transport,worker,batch,shell]) and result['provenance']['plan_sha256']==plan_hash and worker['status']=='completed' and worker['scientific_result_sha256']==sha(W/'result.json') and transport['worker_sha256']==sha(W/'worker.json') and batch['stages'][0]['execution_sha256']==sha(W/'execution.json')
for name,digest in plan['source_sha256'].items():bind(R/name,digest)
for name in ['build_receipt','build_plan']:bind(R/plan[name]['path'],plan[name]['sha256'])
checks['actual_binary_and_all_frozen_sources_bound']=result['provenance']['binary']==plan['binary'] and plan['binary']['sha256']=='4c8779aeac769aadb9e8378282fe6dfef40d336d87bd5914e8145438a66df229' and observation['remote_actual_hashes']['binary_sha256']==plan['binary']['sha256'] and observation['remote_actual_hashes']['source_sha256']==plan['source_sha256'] and result['provenance']['source_sha256']==plan['source_sha256'] and result['provenance']['versions']==plan['versions']
scheduler_override=R/'paper_autonomous_multifork_iteration/evidence/remote_quality_dispatch_20260912/cc103_pending_node_update_attempt1/update_record.json'
bind(scheduler_override);override=read(scheduler_override)
checks['recorded_pending_same_job_scheduler_override_only']=override['status']=='original_pending_24607_unpinned_no_requeue_singleton_retained' and override['science_or_code_changed'] is False and override['jobs_resubmitted'] is False and override['max_simultaneous_GPUs']==1 and any(c['argv']==['scontrol','update','JobId=24607','ReqNodeList=','Requeue=0'] and c['actual_exit_code']==0 and c['actual_parent_wait'] for c in override['commands'])
erratum=T/'independent_review/metadata_erratum.json';bind(erratum,'47a5cdb0a8583f2c16aee2374a75d792c57f075bf041e90e39c9496ffe38abae')
actual_job_rows=[line.split('|') for line in observation['sacct']['stdout'].splitlines() if line.startswith('24607|COMPLETED|0:0|')];assert len(actual_job_rows)==1
actual_node=actual_job_rows[0][-1];assert actual_node.startswith('lj-gpu') and ',' not in actual_node
cases,tails=result['cases'],result['tail_cases']
# These two expressions are the original saved-output numerical/invariance checks.
checks['four_exact_frozen_cases_saved_gates_pass']=len(cases)==4 and all(all(c[k]==v for k,v in p.items()) and c['status']=='passed' and c['defined_code_mismatches']==0 and c['constant_decoded_max_abs_error']==0 and c['scale_equal'] and c['min_equal'] and c['finite_output'] and c['gemv_max_abs_error']<=plan['max_abs_tolerance'] and c['gemv_rms_error']<=plan['rms_tolerance'] and c['own_cuda_tensor_objects_released'] for c,p in zip(cases,plan['cases']))
checks['two_exact_tail_cases_saved_release_and_reuse_gates_pass']=len(tails)==2 and all(all(c[k]==v for k,v in p.items() if k!='requests') and c['status']=='passed' and c['repeat_outputs_bitwise_equal'] and c['entry_tensors_released'] and len(c['requests'])==p['requests'] and all(q['final_tokens']==130 and q['no_entry_alias'] and q['entry_unchanged'] and q['request_tensors_released'] for q in c['requests']) for c,p in zip(tails,plan['tail_cases']))
for c in cases+tails:
 raw=(W/c['raw_path']).resolve();assert raw.parent==W.resolve();bind(raw,c['raw_sha256']);sidecar=raw.with_suffix('.json');bind(sidecar);assert read(sidecar)==c
checks['all_six_raw_file_hashes_and_sidecar_records_match']=len(list(W.glob('*.pt')))==6
phases=worker['phases']
checks['seven_completed_phases_exact_case_order_and_outer_closure']=len(phases)==plan['expected_closed_phases']==7 and [p['phase_id'] for p in phases]==list(range(7)) and all(p['completed'] and p['timing_semantics']=='inclusive_nested_do_not_sum' for p in phases) and phases[0]['name']=='outer_kernel_import_synthetic_checks_and_release' and phases[0]['parent_phase_id'] is None and all(p['parent_phase_id']==0 for p in phases[1:]) and [(p['bits'],p['kind']) for p in phases[1:5]]==[(c['bits'],c['kind']) for c in cases] and [p['bits'] for p in phases[5:]]==[2,4] and result['outer_closed']
checks['post_release_residue_preserved_without_unproven_attribution']=worker['after_tensor_release']==phases[0]['after'] and all(p['after']['allocated_bytes']<=p['peak_allocated_bytes'] and p['after']['reserved_bytes']<=p['peak_reserved_bytes'] for p in phases)
cuda=worker['cuda_policy'];props=worker['actual_torch_properties'];identity=worker['physical_gpu_identity'];resource=plan['resource_policy']
checks['actual_properties_not_legacy_label_bind_target_architecture']=plan['required_compute_capability']==[10,3] and [props['major'],props['minor']]==cuda['compute_capability']==[10,3] and props['uuid'].lower().removeprefix('gpu-')==identity['uuid'].lower().removeprefix('gpu-') and any(line.startswith('24607|COMPLETED|0:0|') and line.endswith('|'+actual_node) for line in observation['sacct']['stdout'].splitlines())
checks['resource_caps_and_fresh_admission']=cuda==result['provenance']['cuda_policy'] and cuda['allocator_backend']=='native' and cuda['allocator_cap_bytes']==resource['allocator_cap_bytes']==200*2**30 and max(p['peak_reserved_bytes'] for p in phases)<=cuda['allocator_cap_bytes'] and transport['stable_interval_seconds']>=45 and all(a['allowed'] and not a['foreign_gpu_compute_processes'] for a in transport['admissions']) and all(a['allowed'] and not a['foreign_gpu_compute_processes'] and a['cuda_free_bytes']>=resource['minimum_free_bytes']==220*2**30 for a in worker['pre_allocation_checks'])
old=R/'paper_autonomous_multifork_iteration/evidence/honly_kivi_remote_preparation_20260912/gpu_qualification_preparation'
checks['original_numerical_source_bridge_and_thresholds_unchanged']=sha(T/'kernel_checks.py')==sha(old/'kernel_checks.py') and sha(T/'bridge.py')==sha(old/'bridge.py') and plan['seed']==149 and plan['max_abs_tolerance']==.01 and plan['rms_tolerance']==.001 and plan['cases']==read(old/'plan.json')['cases'] and plan['tail_cases']==read(old/'plan.json')['tail_cases']
checks['kernel_only_no_model_training_offload_quality_or_profile_claim']=result['cpu_reference_is_oracle_only'] and result['official_cuda_pack_and_gemv_used'] and not result['provenance']['checkpoint_loaded'] and all(worker[k] is False for k in ['model_loaded','training_allowed','runtime_offload_allowed','quality_evidence','profile_evidence']) and all(plan[k] is False for k in ['model_load_allowed','training_allowed','runtime_offload_allowed','automatic_retry'])
checks['current_artifacts_still_match_bound_bytes']=all(sha(R/name)==digest for name,digest in bindings.items())
report={'status':'PASS_saved_remote_target_GPU_kernel_compatibility_completion' if all(checks.values()) else 'FAIL_saved_remote_target_GPU_kernel_compatibility_completion','started_at':start,'finished_at':stamp(),'checker_pid':os.getpid(),'checks':checks,'blockers':[k for k,v in checks.items() if not v],'bindings':bindings,'actual_compute_capability':[props['major'],props['minor']],'actual_Torch_properties':props,'actual_physical_GPU':identity,'verified_Slurm_nodes':[actual_node],'scheduler_override':{'path':scheduler_override.relative_to(R).as_posix(),'sha256':sha(scheduler_override)},'legacy_label_erratum':{'path':erratum.relative_to(R).as_posix(),'sha256':sha(erratum)},'counts':{'synthetic_cases':len(cases),'tail_cases':len(tails),'closed_phases':len(phases),'raw_files_hashed':len(cases)+len(tails)},'cases':[{k:c[k] for k in ['bits','kind','gemv_max_abs_error','gemv_rms_error','defined_code_mismatches']} for c in cases],'after_tensor_release':worker['after_tensor_release'],'legacy_plan_architecture_label':plan.get('architecture'),'legacy_label_scope':'Frozen inherited non-executable label; this report derives actual architecture from worker actual_torch_properties and cuda_policy, checked against required_compute_capability. The old label is not a qualification identity.','parent_exit_evidence':'run_batch returns zero only after held worker success. Frozen batch uses set -e and its sole final foreground command is run_batch; actual shell trap exit0 and Slurm job/batch0 close that parent invocation.','scope':'Only frozen synthetic KIVI Half 2/4-bit shapes, default CUDA stream, actual target-node architecture and exact binary; not model quality, infrastructure, or arbitrary kernels.','not_rechecked':['No GPU or CPU mathematical replay. Six .pt raw files were SHA streamed only, never deserialized.','Numerical, alias, immutability and release gates are source-scoped saved observations, not independent tensor arithmetic.','No model or build, no submission, no global state/paper/automation mutation.','Phase allocated/reserved observations are not full-lifecycle NVML or fixed-work infrastructure measurements.'],'checker_sha256':sha(__file__)}
save(O/'report.json',report);print(json.dumps({'status':report['status'],'checks':len(checks),'blockers':report['blockers']}));raise SystemExit(0 if not report['blockers'] else 1)
